name: "Godot Export Complete"
on: [workflow_dispatch]

env:
  GODOT_VERSION: 3.2.3
  PROJECT_NAME: AutoBattle
  PROJECT_PATH: .
  EXPORT_MODE: debug # If not defined, defaults to debug
  # Required if in release mode
  # K8S_SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_BASE64 }}
  # K8S_SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_USER }}
  # K8S_SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_PASSWORD }}
  GAME_VERSION_TAG: 0.1 # Defined In Godot's Editor Project Settings - Path To Custom Variable
  IOS_ICON_PATH: "icon_path"
  ITCH_GAME: itchio-game
  ITCH_USER: itchio-user

jobs:
  export:
    name: "Godot Project Export"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android,windows,linux,html5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Export Godot Project
      - name: Export ${{ matrix.platform }} Version
        id: export
        uses: vini-guerrero/godot-exporter/actions/export@master
        with:
          platform: ${{ matrix.platform }}

      # Publish Platforms
      #- name: Publish Platforms
      #  uses: vini-guerrero/godot-exporter/actions/publish@master
      #  with:
      #    platform: "Itch"
      #    channel: ${{ matrix.platform }}
      #    project_path: ${{ steps.export.outputs.artifact-path }}

      # Upload Artifact
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: ${{ steps.export.outputs.artifact-path }}
